### ISSUE TITLE
Wanted to check this out but the website is toast due to resources from CDN 404'ing

### ISSUE THREAD

**Issue by nicmendoza** [carlsapp/grizzly-stitch#1]

**Comment by carlsapp** [comment]
Try it now. http://www.grizzlystitch.org/demo.html. The just-in-time transpiling toolchain that we were using before was broken somewhere up the chain. I upgraded everything to use a compiled output with the latest angular build tools. The changes are a quick and dirty fix that need to be cleaned up.

**Comment by nicmendoza** [comment]
Awesome. It works now. Thanks!
